### ISSUE TITLE
Breaking change for 2020

### ISSUE THREAD

**Issue by mitswan** [TMiguelT/AflTablesScraper#1]
Love the module - although it seems to have broken for the 2020 year
![Annotation 2020-06-18 114848](https://user-images.githubusercontent.com/4748540/84968454-de6b4880-b159-11ea-9cc7-fd42d5ac5e62.png)
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-7099f11028f7> in <module>
      1 from afl_tables import MatchScraper
----> 2 rounds = MatchScraper.scrape(2020)

/opt/conda/lib/python3.7/site-packages/afl_tables/__init__.py in scrape(cls, year)
    253             title = header.find('td')
    254 
--> 255             rounds.append(Round.parse(title, body))
    256 
    257         return rounds

/opt/conda/lib/python3.7/site-packages/afl_tables/__init__.py in parse(cls, title, table)
    211             for match in table.select('td[width="85%"] table'):
    212                 try:
--> 213                     matches.append(Match.parse(match))
    214                 except MatchException:
    215                     continue

/opt/conda/lib/python3.7/site-packages/afl_tables/__init__.py in parse(cls, table)
    129         if len(td) == 8:
    130             team_1, team_1_stats, team_1_score, misc, team_2, team_2_stats, team_2_score, winner = td
--> 131             date, _, attendees, _, _, venue = misc
    132 
    133             # Parse the date by taking the first two words (the date), and the last two words (the time in AEST)

ValueError: not enough values to unpack (expected 6, got 4)`

**Comment by multimeric** [comment]
Right, that's breaking because the AFLTables guy didn't put attendee counts in the 2020 matches. Should be a simple fix.

**Comment by multimeric** [comment]
Fixed in 0.0.2.

**Comment by multimeric** [comment]
I've also released on PyPI so you can just `pip install afl_tables`, if that is helpful.

**Comment by mitswan** [comment]
Fantastic - you rock!
